all: hello.c
	@echo "Hello World"
	gcc hello.c -o h

generate:
	@echo "Creating empty text files..."
	touch file-{1..10}.txt

clean:
	@echo "Cleaning up..."
	rm -rf *.o *.out h
	#rm -rf tp1 *~ *.o
	ls